spring:
  application:
    name: QrCodeBulkGenApplication
  profiles:
    active: dev

qr-code:
  workbook-param:
    col-max-read-limit: 3
    col-value-len-before-truncate: 30
    col-header-names:
      - ENCODED TEXT
      - FILENAME
      - QR CODE
    row-max-read-limit: 500
  data-store:
    src-workbook-name: "ListForEncoding.xlsx"
    dst-workbook-name: "QRCodeList.xlsx"
    src-dir: datastore/workbook/
    dst-dir-img: images/
    dst-dir-workbook: datastore/qr-codes/
    qr-code-to-file: true
  image-param:
    format-name: jpg
    filename-prefix: QRCode-
    scale: 10
    border: 2
    light-color: 0xFFFFFF # white
    dark-color: 0x003e2a # green

logging:
  level:
    xyz.joseyamut.qrCodeBulkGen:
      service: debug

